package com.smartstay.controller;

import com.smartstay.dto.common.ApiResponse;
import com.smartstay.dto.passcode.RoomPasscodeDto;
import com.smartstay.model.User;
import com.smartstay.service.AuthService;
import com.smartstay.service.PasscodeService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1")
public class PasscodeController {

    private final PasscodeService passcodeService;
    private final AuthService authService;

    public PasscodeController(PasscodeService passcodeService, AuthService authService) {
        this.passcodeService = passcodeService;
        this.authService = authService;
    }

    @GetMapping("/passcodes/booking/{bookingId}")
    public ResponseEntity<ApiResponse<RoomPasscodeDto>> getPasscode(
            @AuthenticationPrincipal UserDetails userDetails,
            @PathVariable Long bookingId
    ) {
        User user = authService.getAuthenticatedUser(userDetails.getUsername());
        RoomPasscodeDto dto = passcodeService.getPasscodeByBookingId(bookingId, user.getId());
        return ResponseEntity.ok(ApiResponse.ok("Passcode retrieved", dto));
    }

    @PostMapping("/passcodes/booking/{bookingId}/generate")
    public ResponseEntity<ApiResponse<RoomPasscodeDto>> generatePasscode(
            @AuthenticationPrincipal UserDetails userDetails,
            @PathVariable Long bookingId
    ) {
        User user = authService.getAuthenticatedUser(userDetails.getUsername());
        RoomPasscodeDto dto = passcodeService.getPasscodeByBookingId(bookingId, user.getId());
        return ResponseEntity.ok(ApiResponse.ok("Passcode generated", dto));
    }

    @PostMapping("/admin/bookings/{bookingId}/passcode/regenerate")
    public ResponseEntity<ApiResponse<RoomPasscodeDto>> adminRegeneratePasscode(@PathVariable Long bookingId) {
        RoomPasscodeDto dto = passcodeService.regeneratePasscode(bookingId);
        return ResponseEntity.ok(ApiResponse.ok("Passcode regenerated by admin", dto));
    }
}
